app:
  encoding: UTF-8
  debug: true
  trim_str: false
spark:
  executor:
    cores: 5
    memory: 2g
  driver:
    memory: 2g
  max_cores: 5
cassandra:
  host: localhost
  port: 9042
  consistency_level: 'ONE'